// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoTwitts.Ui {
    
    
    public partial class StatusViewItem {
        
        private Gtk.HBox hbox2;
        
        private Gtk.Image image;
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Button username;
        
        private Gtk.HBox hbox4;
        
        private Gtk.Button favorite;
        
        private Gtk.Button direct;
        
        private Gtk.Button reply;
        
        private Gtk.Label text;
        
        private Gtk.Alignment alignment1;
        
        private Gtk.Label dateTime;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MonoTwitts.Ui.StatusViewItem
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoTwitts.Ui.StatusViewItem";
            // Container child MonoTwitts.Ui.StatusViewItem.Gtk.Container+ContainerChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.image = new Gtk.Image();
            this.image.Name = "image";
            this.image.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_smiley-10", Gtk.IconSize.Dialog, 48);
            this.hbox2.Add(this.image);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox2[this.image]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child hbox2.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 20;
            // Container child hbox3.Gtk.Box+BoxChild
            this.username = new Gtk.Button();
            this.username.CanDefault = true;
            this.username.CanFocus = true;
            this.username.Name = "username";
            this.username.Relief = ((Gtk.ReliefStyle)(2));
            this.username.Label = Mono.Unix.Catalog.GetString("$username");
            this.hbox3.Add(this.username);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox3[this.username]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.hbox4 = new Gtk.HBox();
            this.hbox4.Name = "hbox4";
            this.hbox4.Homogeneous = true;
            // Container child hbox4.Gtk.Box+BoxChild
            this.favorite = new Gtk.Button();
            this.favorite.CanFocus = true;
            this.favorite.Name = "favorite";
            this.favorite.Relief = ((Gtk.ReliefStyle)(2));
            // Container child favorite.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-about", Gtk.IconSize.Menu, 16);
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w7.LabelProp = "";
            w4.Add(w7);
            w3.Add(w4);
            this.favorite.Add(w3);
            this.hbox4.Add(this.favorite);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox4[this.favorite]));
            w11.Position = 0;
            w11.Expand = false;
            w11.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.direct = new Gtk.Button();
            this.direct.CanFocus = true;
            this.direct.Name = "direct";
            this.direct.Relief = ((Gtk.ReliefStyle)(2));
            // Container child direct.Gtk.Container+ContainerChild
            Gtk.Alignment w12 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w13 = new Gtk.HBox();
            w13.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w14 = new Gtk.Image();
            w14.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_draw-callouts", Gtk.IconSize.Menu, 16);
            w13.Add(w14);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w16 = new Gtk.Label();
            w16.LabelProp = "";
            w13.Add(w16);
            w12.Add(w13);
            this.direct.Add(w12);
            this.hbox4.Add(this.direct);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox4[this.direct]));
            w20.Position = 1;
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbox4.Gtk.Box+BoxChild
            this.reply = new Gtk.Button();
            this.reply.CanFocus = true;
            this.reply.Name = "reply";
            this.reply.Relief = ((Gtk.ReliefStyle)(2));
            // Container child reply.Gtk.Container+ContainerChild
            Gtk.Alignment w21 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w22 = new Gtk.HBox();
            w22.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w23 = new Gtk.Image();
            w23.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-undo", Gtk.IconSize.Menu, 16);
            w22.Add(w23);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w25 = new Gtk.Label();
            w25.LabelProp = "";
            w22.Add(w25);
            w21.Add(w22);
            this.reply.Add(w21);
            this.hbox4.Add(this.reply);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.hbox4[this.reply]));
            w29.Position = 2;
            w29.Expand = false;
            w29.Fill = false;
            this.hbox3.Add(this.hbox4);
            Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.hbox3[this.hbox4]));
            w30.PackType = ((Gtk.PackType)(1));
            w30.Position = 1;
            w30.Expand = false;
            this.vbox2.Add(this.hbox3);
            Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox3]));
            w31.Position = 0;
            w31.Expand = false;
            w31.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.text = new Gtk.Label();
            this.text.Name = "text";
            this.text.Xalign = 0F;
            this.text.LabelProp = Mono.Unix.Catalog.GetString("$text");
            this.text.UseMarkup = true;
            this.text.Wrap = true;
            this.text.Selectable = true;
            this.text.Ellipsize = ((Pango.EllipsizeMode)(2));
            this.vbox2.Add(this.text);
            Gtk.Box.BoxChild w32 = ((Gtk.Box.BoxChild)(this.vbox2[this.text]));
            w32.Position = 1;
            // Container child vbox2.Gtk.Box+BoxChild
            this.alignment1 = new Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
            this.alignment1.Name = "alignment1";
            this.alignment1.LeftPadding = ((uint)(100));
            // Container child alignment1.Gtk.Container+ContainerChild
            this.dateTime = new Gtk.Label();
            this.dateTime.Name = "dateTime";
            this.dateTime.LabelProp = Mono.Unix.Catalog.GetString("<i>$dateTime</i>");
            this.dateTime.UseMarkup = true;
            this.dateTime.Justify = ((Gtk.Justification)(1));
            this.dateTime.Ellipsize = ((Pango.EllipsizeMode)(3));
            this.alignment1.Add(this.dateTime);
            this.vbox2.Add(this.alignment1);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox2[this.alignment1]));
            w34.PackType = ((Gtk.PackType)(1));
            w34.Position = 2;
            w34.Expand = false;
            w34.Fill = false;
            this.hbox2.Add(this.vbox2);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
            w35.Position = 1;
            this.Add(this.hbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.username.Clicked += new System.EventHandler(this.OnUsernameClicked);
        }
    }
}
